
title: Critical Decentralisation Cluster
email: cluster@decentral.community
description: >- 
  The Critical Decentralisation Cluster on the Chaos Communication Congress (C3) is an area and grouping of different “assemblies”, which are working together and presenting projects, workshops and a space to critically discuss the future of decentralisation.
baseurl: "" 
url: "https://decentral.community"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
